### ISSUE TITLE
Unable to create stack on any other region other than us-west-2

### ISSUE THREAD

**Issue by andreprawira** [awslabs/amazon-kinesis-data-generator#17]
I have been trying to generate the stack provided on the help page on other region other than us-west-2 and it keeps failing. When I generate stack on us-west-1 or us-east-1 I'd get this [error](https://imgur.com/a/8jJUvW2). Also have posted the similar question in AWS dev forum and stackoverflow but no help so far.

**Comment by jaredswarren** [comment]
Apologies for this limitation.  It's definitely possible to implement the cloudformation template in a cross region way - but will take just a bit of effort.  Is there a region or two that you'd like me to prioritize?

**Comment by andreprawira** [comment]
its all good, i had instead generate it on us-west-2, you can cross implement it in any region

**Comment by jaredswarren** [comment]
Support has been added for the following regions:

ap-northeast-1 (Tokyo)
ap-northeast-2 (Seoul)
ap-south-1 (Mumbai)
ap-southeast-1 (Singapore)
ap-southeast-2 (Sydney)
ca-central-1 (Canada Central)
eu-west-1 (Ireland)
eu-west-2 (London)
eu-central-1 (Frankfurt)
us-east-1 (N. Virginia)
us-west-2 (Oregon)
