### ISSUE TITLE
Stream/delivery stream drop-down only contain partial list

### ISSUE THREAD

**Issue by foragerr** [awslabs/amazon-kinesis-data-generator#2]
and does not allow typing in a stream name - making it impossible to select the stream I want.

**Comment by foragerr** [comment]
ListStreams used [here](https://github.com/awslabs/amazon-kinesis-data-generator/blob/master/web/js/producer.js#L274) pages results by default.

http://docs.aws.amazon.com/kinesis/latest/APIReference/API_ListStreams.html

**Comment by MacInnis** [comment]
@foragerr You're correct, it needs to be updated to paginate.  It will be fixed in an upcoming release.

**Comment by MacInnis** [comment]
@foragerr This issue has been resolved.  The list of Streams and Firehose delivery streams is the full list.

**Comment by foragerr** [comment]
thank you!
